import { z } from 'zod';

/**
 * The schema for the usage statistics.
 */
export const UsageStatsSchema = z.object({
  completionTokens: z
    .number()
    .int()
    .positive()
    .describe('The number of tokens generated by the model.'),
  promptTokens: z
    .number()
    .int()
    .positive()
    .describe('The number of tokens generated by the user prompt.'),
  totalTokens: z
    .number()
    .int()
    .positive()
    .describe('The total number of tokens generated.')
});

export type UsageStats = z.infer<typeof UsageStatsSchema>;
