export const ignorePatterns = [
  '**/.!(cursor)/**',
  '**/*.pbxproj',
  '**/node_modules/**',
  '**/dist/**',
  '**/build/**',
  '**/compile/**',
  '**/*.spec.*',
  '**/*.pyc',
  '**/.env',
  '**/.env.*',
  '**/*.env',
  '**/*.env.*',
  '**/*.lock',
  '**/*.lockb',
  '**/package-lock.*',
  '**/pnpm-lock.*',
  '**/*.tsbuildinfo',
  '**/*.log',
  'LICENSE',
  '**/test/**',
  '**/tests/**',
  '**/coverage/**',
  '**/.vscode/**',
  '**/.idea/**',
  '**/.git/**',
  '**/*.ipynb',
  '**/*.sqlite',
  '**/*.db',
  '**/*.sqlite3',
  '**/*.tiktoken',
  '**/*.npz',
  '**/.DS_Store',
  '**/.gitignore',
  '**/.gitattributes',
  '**/.gitmodules',
  '**/.gitkeep',
  '**/.gitpod.yml',
  '**/.png',
  '**/.jpg',
  '**/.jpeg',
  '**/.gif',
  '**/.svg',
  '**/.webp'
];

export const outputOptions = {
  compress: false,
  style: 'markdown',
  fileSummary: false,
  directoryStructure: false,
  removeComments: false,
  removeEmptyLines: true,
  topFilesLength: 20,
  showLineNumbers: false,
  copyToClipboard: false,
  includeEmptyDirectories: false,
  parsableStyle: false
} as const;
